[package]
name = "http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
neural_network = { path = "../project" }
#rocket = { version = "0.5.1", features = ["derive"] }
rocket = { version = "0.5.1", features = ["json"] }
